{{- if and (.Values.proxy.enabled) (.Values.proxy.autoscaling.enabled) }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "milvus.proxy.fullname" . }}
  labels:
    {{ include "milvus.labels" . | indent 4 }}
    component: "proxy"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "milvus.proxy.fullname" . }}
  minReplicas: {{ .Values.proxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.proxy.autoscaling.maxReplicas }}
  metrics:
{{ toYaml .Values.proxy.autoscaling.metrics | indent 4 }}
{{- end }}

{{- if and (.Values.queryNode.enabled) (.Values.queryNode.autoscaling.enabled) }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "milvus.querynode.fullname" . }}
  labels:
    {{ include "milvus.labels" . | indent 4 }}
    component: "querynode"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "milvus.querynode.fullname" . }}
  minReplicas: {{ .Values.queryNode.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.queryNode.autoscaling.maxReplicas }}
  metrics:
{{ toYaml .Values.queryNode.autoscaling.metrics | indent 4 }}
{{- end }}

{{- if and (.Values.indexNode.enabled) (.Values.indexNode.autoscaling.enabled) }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "milvus.indexnode.fullname" . }}
  labels:
    {{ include "milvus.labels" . | indent 4 }}
    component: "indexnode"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "milvus.indexnode.fullname" . }}
  minReplicas: {{ .Values.indexNode.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.indexNode.autoscaling.maxReplicas }}
  metrics:
{{ toYaml .Values.indexNode.autoscaling.metrics | indent 4 }}
{{- end }}

{{- if and (.Values.dataNode.enabled) (.Values.dataNode.autoscaling.enabled) }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "milvus.datanode.fullname" . }}
  labels:
    {{ include "milvus.labels" . | indent 4 }}
    component: "datanode"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "milvus.datanode.fullname" . }}
  minReplicas: {{ .Values.dataNode.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dataNode.autoscaling.maxReplicas }}
  metrics:
{{ toYaml .Values.dataNode.autoscaling.metrics | indent 4 }}
{{- end }}