{{- if .Values.insight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus.insight.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "insight"
spec:
{{- if (or (eq .Values.insight.service.type "ClusterIP") (empty .Values.insight.service.type)) }}
  type: ClusterIP
  {{- if .Values.insight.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
{{- else if eq .Values.insight.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- if .Values.insight.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
{{- if .Values.insight.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.insight.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.insight.service.type }}
{{- end }}
  ports:
    - name: insight
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
{{ include "milvus.matchLabels" . | indent 4 }}
    component: "insight"
{{- end }}