{{- if and .Values.insight.enabled .Values.insight.ingress.enabled }}
{{- $insightServiceName := include "milvus.insight.fullname" . -}}
{{- $insightServicePort := .Values.insight.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "milvus.insight.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
{{- if .Values.insight.ingress.labels }}
{{ toYaml .Values.insight.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.insight.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.insight.ingress.tls }}
  tls:
  {{- range .Values.insight.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  backend:
    serviceName: {{ $insightServiceName }}
    servicePort: {{ $insightServicePort }}
{{- if .Values.insight.ingress.hosts }}
  rules:
  {{- range $host := .Values.insight.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: {{ $insightServiceName }}
            servicePort: {{ $insightServicePort }}
  {{- end -}}
{{- end -}}
{{- end }}