{{- if .Values.insight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.insight.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "insight"
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: "insight"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "insight"
    spec:
      {{- if .Values.insight.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.insight.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: insight
        image: {{ .Values.insight.image.repository }}:{{ .Values.insight.image.tag }}
        imagePullPolicy: {{ .Values.insight.image.pullPolicy }}
        ports:
        - name: insight
          containerPort: 3000
          protocol: TCP
        env:
{{ include "milvus.insight.env" . | indent 8}}
        resources:
          {{- toYaml .Values.insight.resources | nindent 10 }}
    {{- if and (.Values.affinity) (not .Values.insight.affinity) }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.insight.affinity }}
      affinity:
{{ toYaml .Values.insight.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.tolerations) (not .Values.insight.tolerations) }}
    tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.insight.tolerations }}
      tolerations:
{{ toYaml .Values.insight.tolerations | indent 8 }}
    {{- end }}
{{- end }}
