{{- if and .Values.rootCoordinator.enabled .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.rootcoord.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "rootcoord"
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: "rootcoord"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "rootcoord"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.image.all.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.all.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: rootcoord
        image: "{{ .Values.image.all.repository }}:{{ .Values.image.all.tag }}"
        imagePullPolicy: {{ .Values.image.all.pullPolicy }}
        args: [ "milvus", "run", "rootcoord" ]
        {{- if .Values.rootCoordinator.extraEnv }}
        env:
          - name: CACHE_SIZE
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
                divisor: 1Gi
          {{- toYaml .Values.rootCoordinator.extraEnv | nindent 10 }}
        {{- end }}
        ports:
          - name: rootcoord
            containerPort: 53100
            protocol: TCP
          {{- if .Values.metrics.enabled }}
          - name: metrics
            containerPort: 9091
            protocol: TCP
          {{- end }}
        resources:
          {{- toYaml .Values.rootCoordinator.resources | nindent 10 }}
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
          readOnly: true
        {{- if .Values.log.persistence.enabled }}
        - name: milvus-logs-disk
          mountPath: {{ .Values.log.persistence.mountPath | quote }}
          subPath: {{ .Values.log.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}

      {{- with .Values.rootCoordinator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rootCoordinator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rootCoordinator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: milvus-config
        configMap:
          name: {{ template "milvus.fullname" . }}
      {{- if .Values.log.persistence.enabled }}
      - name: milvus-logs-disk
        persistentVolumeClaim:
          claimName: {{ .Values.log.persistence.persistentVolumeClaim.existingClaim | default (printf "%s-logs" (include "milvus.fullname" . | trunc 58)) }}
      {{- end }}
{{- end }}