{{- if not .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.standalone.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "standalone"
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: "standalone"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "standalone"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.image.all.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.all.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: standalone
        image: "{{ .Values.image.all.repository }}:{{ .Values.image.all.tag }}"
        imagePullPolicy: {{ .Values.image.all.pullPolicy }}
        args: [ "milvus", "run", "standalone" ]
        {{- if .Values.standalone.extraEnv }}
        env:
          {{- toYaml .Values.standalone.extraEnv | nindent 10 }}
        {{- end }}
        ports:
          - name: milvus
            containerPort: 19530
            protocol: TCP
          {{- if .Values.metrics.enabled }}
          - name: metrics
            containerPort: 9091
            protocol: TCP
          {{- end }}
        resources:
          {{- toYaml .Values.standalone.resources | nindent 10 }}
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
          readOnly: true
        - name: milvus-data-disk
          mountPath: {{ .Values.standalone.persistence.mountPath | quote }}
          subPath: {{ .Values.standalone.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- if .Values.log.persistence.enabled }}
        - name: milvus-logs-disk
          mountPath: {{ .Values.log.persistence.mountPath | quote }}
          subPath: {{ .Values.log.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}

      {{- with .Values.standalone.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.standalone.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.standalone.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: milvus-config
        configMap:
          name: {{ template "milvus.fullname" . }}
      - name: milvus-data-disk
        {{- if .Values.standalone.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.standalone.persistence.persistentVolumeClaim.existingClaim | default (printf "%s" (include "milvus.fullname" . | trunc 58)) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.log.persistence.enabled }}
      - name: milvus-logs-disk
        persistentVolumeClaim:
          claimName: {{ .Values.log.persistence.persistentVolumeClaim.existingClaim | default (printf "%s-logs" (include "milvus.fullname" . | trunc 58)) }}
      {{- end }}
{{- end }}