pull_request_rules:
  - name: add ci-pass when CI 'Broken Links' passed
    conditions:
        - check-success=Broken Links
    actions:
      label:
        add:
          - ci-passed

  - name: add ci-pass when CI 'lint-test' passed
    conditions:
        - check-success=lint-test
    actions:
      label:
        add:
          - ci-passed

  - name: remove ci-pass when CI not passed
    conditions:
      - and:
        - or:
          - files=charts/**
          - files=ct.yaml
          - files=.github/workflows/lint-test.yml
          - files!=**.md
          - files!=**.txt
        - check-success!=lint-test
    actions:
      label:
        remove:
          - ci-passed
  
  - name: remove ci-pass when CI-2 not passed
    conditions:
      - and:
        - files=**.md
        - check-success!=Broken Links
    actions:
      label:
        remove:
          - ci-passed