cache:
  insertBufferSize: 1GB
  cacheSize: 8GB

image:
  resources:
    limits:
      memory: "12Gi"
      cpu: "4.0"
    requests:
      memory: "8Gi"
      cpu: "2.0"

gpu:
  enabled: false

mysql:
  enabled: false
