{{- $pvc := .Values.persistence.persistentVolumeClaim -}}
{{- if and .Values.persistence.enabled (not $pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "milvus.sharename" . }}
{{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
spec:
  accessModes:
  - {{ $pvc.accessModes | quote }}
  {{- if $pvc.storageClass }}
    {{- if eq "-" $pvc.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $pvc.storageClass }}
    {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
