name: Markdown Links Check

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'