name: Helm

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'templates/**'
      - 'Chart.yaml'
      - 'requirements.yaml'
      - 'values.yaml'
      - '.github/workflows/helm.yml'
      - '!**.txt'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'templates/**'
      - 'Chart.yaml'
      - 'requirements.yaml'
      - 'values.yaml'
      - '.github/workflows/helm.yml'
      - '!**.txt'

jobs:
  lint-helm:
    name: AMD64 Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout Milvus Helm
        uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v1
        with:
          exec: helm lint .
